# Generated by Django 4.2.16 on 2024-10-14 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id_filmu', models.AutoField(primary_key=True, serialize=False)),
                ('tytul', models.CharField(max_length=255)),
                ('gatunek', models.CharField(max_length=100, null=True)),
                ('rok_wydania', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id_uzytkownika', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id_oceny', models.AutoField(primary_key=True, serialize=False)),
                ('ocena', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('id_filmu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.film')),
                ('id_uzytkownika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.uzytkownik')),
            ],
        ),
    ]
